config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  
  #Yin Yin Aye 
  get '/workspacecreate',    to: 'users#workspacecreate'
  get '/managemember',    to: 'users#managemember'
  get '/home',    to: 'users#home'
  post '/home',    to: 'users#home'
  get  '/welcome',    to: 'users#welcome'
  get  '/memberlist1',    to: 'users#memberlist1'
  get  '/addmember',    to: 'users#addmember'
  get  '/memberadd',    to: 'users#add'
  get  '/remove',    to: 'users#remove'
  delete  '/remove',    to: 'users#remove'
  get  '/admin',    to: 'users#admin'
  patch  '/admin',    to: 'users#admin' 
  
  #Thu Zin Tun
  get  '/invitesuccess',    to: 'users#invitesuccess'
  get  '/memberinvite',    to: 'users#memberinvite' 
  get 'sessions/new'
  get  '/signup',  to: 'muser#new'
  get  '/show',  to: 'muser#show'
  post  '/create',  to: 'muser#create'
  get  '/workspacecreate',  to: 'muser#workspacecreate' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy' 
  get  '/searchworkspace',    to: 'users#searchworkspace' 
  post  '/searchworkspace',    to: 'muser#search' 
  
  #Aye Aye Mu
  #get  '/searchworkspace',    to: 'users#searchworkspace'
  #get  '/newworkspace',    to: 'users#newworkspace'
  #get  '/channelcreate',    to: 'users#channelcreate'
  #post  '/channelcreate',    to: 'users#channelcreate'
  get  '/member',    to: 'users#member'

  #KMMG
  get '/newworkspace', to: 'sessions#newworkspace'
  post '/newworkspace', to: 'sessions#newworkspace'
  post  '/channelcreate',    to: 'sessions#channelcreate'
  get  '/channelcreate',    to: 'sessions#channelcreate'

  get  '/chchannel',    to: 'channel#chchannel'
  post  '/chchannel',    to: 'channel#chchannel'
  get  '/createchannel',    to: 'channel#createchannel'
  post  '/createchannel',    to: 'channel#createchannel'

  #chat
  #cna
  get '/channelchat',    to: 'users#channel_chat'
  post '/channelchat',    to: 'users#channel_chat'
  get '/dirchat',    to: 'users#dirchat'
  post '/dirchat',    to: 'users#dirchat'
  get '/msgsend',    to: 'users#msgsend'
  post '/msgsend',    to: 'users#msgsend'
  get '/dirmsgsend',    to: 'users#dirmsgsend'
  post '/dirmsgsend',    to: 'users#dirmsgsend'



  resources :workspaces
  resources :m_users
  resources :m_channels
  resources :account_activations, only: [:edit]
  resources :t_channel_msg,          only: [:msgsend, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def new
        
    end

    def create
    end

    def login
    end

    def home
        list
    end
    
    #chonweaung
    def channel_chat
        
        channelchat = MChannel.find_by(id:params[:channel_id])
        channel channelchat
        @channel_msg_read = TChannelMsg.select("m_users.user_name,t_channel_msgs.channel_msg,t_channel_msgs.created_at").
                    joins("join m_users on t_channel_msgs.sender_id = m_users.id").
                    joins("join t_channel_unread_msgs on t_channel_msgs.id = t_channel_unread_msgs.channel_msg_id ").
                    where("t_channel_unread_msgs.unread = 0 and t_channel_msgs.channel_id = ?
                    and t_channel_unread_msgs.unread_user_id = ?", session[:channel_id], session[:muser_id])

        @channel_msg_unread = TChannelMsg.select("m_users.user_name,t_channel_msgs.channel_msg,t_channel_msgs.created_at").
                    joins("join m_users on t_channel_msgs.sender_id = m_users.id").
                    joins("join t_channel_unread_msgs on t_channel_msgs.id = t_channel_unread_msgs.channel_msg_id ").
                    where("t_channel_unread_msgs.unread = 1 and t_channel_msgs.channel_id = ?
                    and t_channel_unread_msgs.unread_user_id = ?", session[:channel_id], session[:muser_id])
        
        TChannelUnreadMsg.where(:unread_user_id=>session[:muser_id]).update_all(:unread=>0)


        list
    end

    def msgsend
        
        @channel_msg = TChannelMsg.new
        @channel_msg.channel_id = session[:channel_id]
        @channel_msg.sender_id = session[:muser_id]
        @channel_msg.channel_msg = params[:tchamsg][:msg]
        @channel_msg.save
        last_id = TChannelMsg.maximum("id")
        channel_memberlist
        @member_list.each do |memberlist|
            @channel_unread = TChannelUnreadMsg.new
            @channel_unread.channel_msg_id = last_id
            @channel_unread.unread_user_id = memberlist.userid
            @channel_unread.unread = 1
            @channel_unread.save
        end
        puts "last id"
        puts last_id
    end

    #dirmsg
    def dirchat
        diruser= MUser.find_by(id:params[:id])
        dir diruser
        @dir_msg_read = TDirectMsg.select("sender.user_name as s, receiver.user_name as r, t_direct_msgs.message, t_direct_msgs.created_at").
                    joins("join m_users as sender on t_direct_msgs.sender_id = sender.id").
                    joins("join m_users as receiver on t_direct_msgs.receiver_id = receiver.id ").
                    where("t_direct_msgs.unread=0 and (t_direct_msgs.sender_id = ?
                    and t_direct_msgs.receiver_id = ?
                    or t_direct_msgs.sender_id = ?
                    and t_direct_msgs.receiver_id = ?)
                    and t_direct_msgs.workspace_id = ?",
                     session[:diruser_id], session[:muser_id], session[:muser_id], session[:diruser_id], session[:workspace_id])
        
        @dir_msg_unread = TDirectMsg.select("m_users.user_name, t_direct_msgs.message, t_direct_msgs.created_at").
                     joins("join m_users on t_direct_msgs.sender_id = m_users.id").
                     where("t_direct_msgs.unread=1 and t_direct_msgs.sender_id = ?
                     and t_direct_msgs.receiver_id = ?
                     and t_direct_msgs.workspace_id = ?",
                      session[:diruser_id], session[:muser_id], session[:workspace_id])

        @dir_msg_sent = TDirectMsg.select("m_users.user_name, t_direct_msgs.message, t_direct_msgs.created_at").
                      joins("join m_users on t_direct_msgs.sender_id = m_users.id").
                      where("t_direct_msgs.unread=1 and t_direct_msgs.sender_id = ?
                      and t_direct_msgs.receiver_id = ?
                      and t_direct_msgs.workspace_id = ?",
                      session[:muser_id], session[:diruser_id], session[:workspace_id])
        
        TDirectMsg.where(:receiver_id=>session[:muser_id], :sender_id=>session[:diruser_id]).update(:unread=>0)
        #redirect-back(fallback_location: fallback_location)
        list
    end

    def dirmsgsend
        @dir_msg = TDirectMsg.new
        @dir_msg.sender_id = session[:muser_id]
        @dir_msg.receiver_id = session[:diruser_id]
        @dir_msg.workspace_id = session[:workspace_id]
        @dir_msg.message = params[:dirmsg][:msg]
        @dir_msg.unread = 1
        @dir_msg.save
        @dir_msg.reload

    end

    
    def memberlist
    end

    def memberlist1
        list
        channel_memberlist
    end

    def addmember
        list
        channel_memberlist
        exist
    end
    def add
        user_id = params[:user_id]
        @add = MChannel.new(:id=>7, :user_id=>user_id, :workspace_id=>session[:workspace_id], :channel_name=>"Channel7", :status=>1)
        @add.save
        redirect_to addmember_path
    end
    def remove
        member_id=params[:user_id]
        MChannel.where(:id=>7, :user_id=>member_id).delete_all
        flash[:success] = "User deleted"
        redirect_to memberlist1_path
    end
    def admin
        admin_id=params[:user_id]
        MWorkspace.where(:id=>session[:workspace_id],:user_id=>admin_id).update_all(:admin=>admin_id)
        flash[:success] = "Admin Changed"
        redirect_to managemember_path
    end

    def managemember
        list
        @admin=MWorkspace.select("user_id").joins("join m_users on m_users.id=m_workspaces.user_id").
                where("m_workspaces.admin=1 and m_workspaces.id=?",session[:workspace_id])
    end

    def welcome
    end

    def workspacecreate
    end

    def searchworkspace  
    end

    private  
    
    def list 
        @muser=MUser.select("m_users.id, m_users.user_name").joins("join m_workspaces on m_users.id=m_workspaces.user_id ").
                where("m_workspaces.id=?",session[:workspace_id])

        @mchannel=MChannel.select("id,channel_name,status").
                where("workspace_id=? and user_id=?",session[:workspace_id], session[:muser_id])
        
        @dir_count=TDirectMsg.select("sum(unread) as count, m_users.user_name").
                    joins("join m_users on m_users.id=t_direct_msgs.sender_id").
                    where("t_direct_msgs.unread=1 and t_direct_msgs.workspace_id=?
                     and t_direct_msgs.receiver_id=?", session[:workspace_id], session[:muser_id]).
                     group("t_direct_msgs.sender_id")
                     
        @channel_count=TChannelUnreadMsg.select("sum(unread)as count,t_channel_msgs.channel_id").
                        joins("join t_channel_msgs on t_channel_msgs.id=t_channel_unread_msgs.channel_msg_id").
                        where("t_channel_unread_msgs.unread=1 and t_channel_unread_msgs.unread_user_id=?", session[:muser_id]).
                        group("t_channel_msgs.channel_id")
    end

    def channel_memberlist
        #@member_list = MChannel.find_by_sql("select m_users.id as userid, m_users.user_name
        #from m_channels,m_users where m_channels.id=8 and m_users.id = m_channels.user_id")

        @member_list = MChannel.select("m_users.id as userid, m_users.user_name").
        joins("join m_users on m_users.id = m_channels.user_id").
        where("m_channels.id=?",session[:channel_id]) 
    end

    def exist
        @exist=MChannel.select("user_id").
        where("m_channels.id = ? and workspace_id=?", session[:channel_id], session[:workspace_id])
        
    end

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/addmember.html.erb
<div class="container-fluid bd">
    <div class="row">
        <div class="col-sm-2 col-md-2 hleft">
            <%= render 'listed/list_info' %>
        </div>
        <div class="col-sm-10 col-md-10 hright">
        
            <div class="container-fluid member">
                <header class="container-fluid row">
                    <div class="col-md-10">
                        <h3><%= @mchannel.first.channel_name %></h3>
                        <h5><%= link_to "Channel Member List", memberlist1_path, class: "mlink" %></h5>
                    </div>
                    <div class="col-md-2 mstar">
                        <%= link_to "@", '#', class: "mlink" %>
                        <%= link_to "",'#', :class => "fa fa-star btnstar" %>
                    </div>
                </header>
                <div class="dframe">
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4">
                            <h4>Add Member from <%= session[:workspace_name]%></h4>
                        </div>        
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-2">
                        <ul>
                        <% @muser.each do |muser|%>
                            
                            <li>
                                <%= muser.user_name %>   
                                        <% if @exist.map(&:user_id).include? muser.id %>            
                                        <%= link_to "Already Exist",'#',class: "btn btn-warning disabled btnAdd" %>
                                
                                        <% else %>
                                        <%= link_to 'Add', memberadd_url(:user_id => muser.id) %>
                                           
                                        <% end %> 
                            </li>
                        <% end %>
                        </ul>
                    </div>               
                </div>           
            </div>
        </div>
    </div>
</div>

app/views/users/channel_chat.html.erb
<div class="container-fluid bd">
    <div class="row">
        <div class="col-sm-2 col-md-2 hleft">
            <%= render 'listed/list_info' %>
        </div>
        <div class="col-sm-10 col-md-10 hright">
            <div class="container-fluid member">
                <header class="container-fluid row">
                    <div class="col-md-10">
                    <h3><%= session[:channel_name] %></h3>
                    <h5><%= link_to "Channel Member List", memberlist1_path, class: "mlink" %></h5>
                    </div>
                    <div class="col-md-2 mstar">
                        <%= link_to "@", '#', class: "mlink" %>
                        <%= link_to "",'#', :class => "fa fa-star btnstar" %>
                    </div>
                </header>

            <div>
                <br>
                    <% @channel_msg_read.each do |channelmsgread|%>
                    <%= channelmsgread.user_name %>
                    <%= channelmsgread.channel_msg %>
                    Posted <%= time_ago_in_words(channelmsgread.created_at) %> ago.
                    <br>
                <% end %>
               
                <% @channel_msg_unread.each do |channelmsgunread|%>
                    <%= channelmsgunread.user_name %>
                    <%= channelmsgunread.channel_msg %>
                    <br>
                <% end %>
                
            </div>

                
                <div class="footer">
                    <div class col="col-md-8 col-md-offset-5", style="margin-top:20pm">
                        <%= form_for(:tchamsg,url:msgsend_path) do |f| %>
                            <%= f.text_area :msg ,class:"tatag"%>
                            <%= f.submit "Send",class: "btn btn-lg btn-primary btnsent"%>
                        <% end %>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>

app/views/users/channelcreate.html.erb
<% provide(:title, 'New WorkSpace') %>

<div class="channel_create">
  
  <div class="row new_channel">
    <div class="col-md-5 col-md-offset-4">
      <h1>New Channel</h1>
      <br><br>
      <%= form_for(:workspace, url: home_path) do |f| %>
          <%= f.label :name, "Channel Name:" %>
          <%= f.text_field :name, class: "form-control" %>  

          <div class="row">
            <div class="col-md-5 text-center">
              <%= f.radio_button :status, "Public", :checked => true %>
              <%= f.label :status, "Public" %>
            </div>
            <div class="col-md-5 text-center">
              <%= f.radio_button :status, "Private"%>
              <%= f.label :status, "Private" %>
            </div>
          </div>
          <%= f.submit "Create", class:"btn btn-primary btn-lg btn-block"  %>
        <% end %>
      </div>
    </div>
</div>
  

app/views/users/home.html.erb
<div class="container-fluid bd">
    <div class="row">
        <div class="col-sm-2 col-md-2 hleft">
            <%= render 'listed/list_info' %>
        </div>
        <div class="col-sm-10 col-md-10 hright">
            <div class="container-fluid member">
                <header class="container-fluid row">
                    <div class="col-md-10">
                    <h3><%= @mchannel.first.channel_name %></h3>
                    <h5><%= link_to "Channel Member List", memberlist1_path, class: "mlink" %></h5>
                    </div>
                    <div class="col-md-2 mstar">
                        <%= link_to "@", '#', class: "mlink" %>
                        <%= link_to "",'#', :class => "fa fa-star btnstar" %>
                    </div>
                </header>
                <div class="container-fluid row dframe">
                    
                </div>
                <div class="footer font-small indigo row">
                    <div class="col-md-10"><%= text_area_tag(:text, "", class:"tatag") %></div>
                    <div class="col-md-2"><%= link_to "Send", '#', class: "btn btn-lg btn-primary btnsend" %></div>
                </div>
            </div> 
        </div>
    </div>
</div>

app/views/users/login.html.erb
<div class="row login">
  <div class="col-md-6 col-md-offset-3">
    <h1>Log in</h1>
    <br><br>
    <%= form_for(:user, url: '#') do |f| %>
      <%= f.label :email, "Email:" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.submit "Log in", class: "btn btn-primary form-control" %>
    <% end %>
    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
  
</div>

app/views/users/managemember.html.erb
<div class="container-fluid bd">
    <div class="row">
        <div class="col-sm-2 col-md-2 hleft">
            <%= render 'listed/list_info' %>
        </div>
        <div class="col-sm-10 col-md-10 hright">

            <div class="container-fluid member">
                <header class="container-fluid row">
                <div class="col-md-10">
                    <h3>Manage Member</h3>
                </div>
                <div class="col-md-2 mstar">
                    <%= link_to "@", '#', class: "mlink" %>
                    <%= link_to "",'#', :class => "fa fa-star btnstar" %>
                </div>
                </header>
                <div class="dframe">
                    <%= label :name, "Name" %><br><br><br><br>
                    <div class="row">
                        <div class="col-sm-4">
                        <ul>
                        <% @muser.each do |muser|%>   
                            <li>
                                <%= muser.user_name %>   
                                        <% if @admin.map(&:user_id).include? muser.id %>            
                                        &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<%=  "Admin " %>
                                        <% else %>
                                        &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp<%= link_to "User",admin_url(:user_id => muser.id),method: :patch %> 
                                <% end %> 
                            </li>
                        <% end %>
                        </ul>

                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

app/views/users/member.html.erb
<% provide(:title, "Search Your WorkSpace") %>

<div class="row mpage">
<h1>Join the Slack WorkSpace <span>Workspace Name　</span></h1>
<br><br>
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(:workspace, url: "#") do |f| %>
      <%= f.label :name, "Full Name:" %>
      <%= f.text_field :name, class: "form-control" %>    
      <%= f.label :password, "Password(required):" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Join", class:"btn btn-primary btn-lg btn-block" %>
      <% end %>
  </div>
  </div>

app/views/users/memberinvite.html.erb
<% provide(:title, 'MemberInvite') %>

<div class="container memberinvite">
<div>
  <h1>Invite Member to <b>ChannelName</b></h1>
  <br><br>
</div>
<div class="formgp">
<%= form_for(:user,url:'#') do |f| %>

<div class="emailform">
<div class="col">
  <%= f.label :EmailAddress,"Email Address:" %>
  <br>
  <%= f.email_field :email,value:"name@example.com", class: "form-control" %>
</div>
<br>
<br>
<div class="col">
  <%= f.label :EmailAddress,"Email Address:" %>
  <br>
  <%= f.email_field :email,value:"name@example.com", class: "form-control" %>
</div>
<br>
<br>
<div class="col">
  <%= f.label :EmailAddress,"Email Address:" %>
  <br>
  <%= f.email_field :email,value:"name@example.com", class: "form-control" %>
</div>
<br>
<br>
<p><%= link_to "Send Invitations", '#', class: "btn btn-lg btn-primary" %></p>
</div>
</div>
  </div>
  
<% end %>  

</div>

app/views/users/memberlist1.html.erb
<div class="container-fluid bd">
    <div class="row">
        <div class="col-sm-2 col-md-2 hleft">
            <%= render 'listed/list_info' %>
        </div>
        <div class="col-sm-10 col-md-10 hright">
            <div class="container member">
                <header class="container-fluid row">
                    <div class="col-md-10">
                    <h3><%= session[:channel_name] %></h3>
                    <h5><%= link_to "Channel Member List", memberlist1_path, class: "mlink" %></h5>
                    </div>
                    <div class="col-md-2 mstar">
                        <%= link_to "@", '#', class: "mlink" %>
                        <%= link_to "",'#', :class => "fa fa-star btnstar" %>
                    </div>
                </header>
                <div class="container-fluid row memberlist1">
                    <div class="col-sm-4">
                        <ul>
                        <li><i class="fa fa-user"></i> <%= @member_list.size %> Members &nbsp &nbsp &nbsp &nbsp &nbsp<%= link_to '',addmember_path, :class=> "fa fa-plus mlink" %></li>
                            <% @member_list.each do |memberlist|%>
                                <li>
                                <%= memberlist.user_name %>&nbsp &nbsp &nbsp &nbsp &nbsp<%= link_to '',remove_url(:user_id => memberlist.userid),method: :delete,data: {confirm: "You sure?"},:class=> "fa fa-minus mlink" %>
                                </li>
                                <% end %>
                        </ul>
                    </div>
            
                </div>   
            </div>

        </div>
    </div>
</div>

app/views/users/newworkspace.html.erb
<% provide(:title, 'New WorkSpace') %>

<div class="row new_workspace">
  <div class="col-md-6 col-md-offset-3">
  <h1>New WorkSpace</h1>
  <br><br>
  <%= form_for(:mworkspace, url: channelcreate_path) do |f| %>
      <%= f.label :name, "New WorkSpace:" %>
      <%= f.text_field :name, class: "form-control" %>     
      <%= f.submit "Next", class:"btn btn-primary btn-lg btn-block"  %>
      <% end %>
  </div>
  </div>
  
  
  

app/views/users/searchworkspace.html.erb
<% provide(:title, "Search Your WorkSpace") %>

<div class="row searchworkspace">
  <div class="col-md-6 col-md-offset-3">
  <h1>Search Your WorkSpace</h1>
  <br><br>
  <%= form_for(:workspace, url: searchworkspace_path) do |f| %>
      <%= f.label :workspace_name, "Workspace Name:" %>
      <%= f.text_field :workspace_name, class: "form-control" %>    
      <%= f.label :email, "Email:" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Search", class:"btn btn-primary btn-lg btn-block" %>
      <% end %>
  </div>
  </div>

app/views/users/signup.html.erb
<% provide(:title, 'Sign up') %>


<div class="row signup">
  <div class="col-md-6 col-md-offset-3">
  <h1>Sign Up</h1><br><br>
    <%= form_for(:user,url:'#') do |f| %>
      <%= f.label :UserName,"UserName:" %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :Email,"Email:" %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :Password ,"Password:"%>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :ComfirmPassword ,"Comfirm Password:"%>
      <%= f.password_field :comfirmpassword, class: "form-control" %> 

      <%= f.submit "SignUp", class: "btn btn-primary form-control" %>
    <% end %>
  </div>

</div>

app/views/users/welcome.html.erb
<div class="welcome">
  <h3><b>Slack_App</b>
  </h3>
  <p>
  <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
  </p>
  <br><br>
  <div>
    
    <h1>Welcome to Slack App</h1>

    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary button1" %>
  </div>
</div>

app/views/users/workspacecreate.html.erb
<div class="container wframe">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <%= link_to "WorkSpace Create", newworkspace_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 

    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <%= link_to "Search Your WorkSpace", searchworkspace_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 
</div>