config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  
  #Yin Yin Aye 
  get '/workspacecreate',    to: 'users#workspacecreate'
  get '/managemember',    to: 'users#managemember'
  get '/home',    to: 'users#home'
  post '/home',    to: 'users#home'
  get  '/welcome',    to: 'users#welcome'
  get  '/memberlist1',    to: 'users#memberlist1'
  get  '/addmember',    to: 'users#addmember'
  get  '/memberadd',    to: 'users#add'
  get  '/remove',    to: 'users#remove'
  delete  '/remove',    to: 'users#remove'
  get  '/admin',    to: 'users#admin'
  patch  '/admin',    to: 'users#admin' 
  
  #Thu Zin Tun
  get  '/invitesuccess',    to: 'users#invitesuccess'
  get  '/memberinvite',    to: 'users#memberinvite' 
  get 'sessions/new'
  get  '/signup',  to: 'muser#new'
  get  '/show',  to: 'muser#show'
  post  '/create',  to: 'muser#create'
  get  '/workspacecreate',  to: 'muser#workspacecreate' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy' 
  get  '/searchworkspace',    to: 'users#searchworkspace' 
  post  '/searchworkspace',    to: 'muser#search' 
  
  #Aye Aye Mu
  #get  '/searchworkspace',    to: 'users#searchworkspace'
  #get  '/newworkspace',    to: 'users#newworkspace'
  #get  '/channelcreate',    to: 'users#channelcreate'
  #post  '/channelcreate',    to: 'users#channelcreate'
  get  '/member',    to: 'users#member'

  #KMMG
  get '/newworkspace', to: 'sessions#newworkspace'
  post '/newworkspace', to: 'sessions#newworkspace'
  post  '/channelcreate',    to: 'sessions#channelcreate'
  get  '/channelcreate',    to: 'sessions#channelcreate'

  get  '/chchannel',    to: 'channel#chchannel'
  post  '/chchannel',    to: 'channel#chchannel'
  get  '/createchannel',    to: 'channel#createchannel'
  post  '/createchannel',    to: 'channel#createchannel'

  #chat
  #cna
  get '/channelchat',    to: 'users#channel_chat'
  post '/channelchat',    to: 'users#channel_chat'
  get '/dirchat',    to: 'users#dirchat'
  post '/dirchat',    to: 'users#dirchat'
  get '/msgsend',    to: 'users#msgsend'
  post '/msgsend',    to: 'users#msgsend'
  get '/dirmsgsend',    to: 'users#dirmsgsend'
  post '/dirmsgsend',    to: 'users#dirmsgsend'



  resources :workspaces
  resources :m_users
  resources :m_channels
  resources :account_activations, only: [:edit]
  resources :t_channel_msg,          only: [:msgsend, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/listed/_list_info.html.erb
<div class="container details">
    <div class="dropdown btnDrop">
        <div class="dropdown-toggle wlink" data-toggle="dropdown">
            <div class="row">
                <div class="col-md-10"><span class="wname">
                    <%= session[:workspace_name] %>
                    <br>
                    <%= session[:muser_name] %>
                </span></div>
                <div class="col-md-2"> <b class="caret car"></b></div>
            </div>
        </div>
        <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to "Manage Member", managemember_path, class: "alink" %></li>
              <li><%= link_to "SignIn other workspace", '#', class: "alink" %></li>
              <li>
                <%= link_to "Sign Out", '#', class: "alink" %>
              </li>
        </ul>
    </div>
    
    <div class="thread_unread">
        <div>
            <%= link_to "Thread", '#', class: "alink" %>
        </div>

        <div>
            <%= link_to "Unread", '#', class: "alink" %>
        </div>
    </div>
    

    <div class="channel">
        <h3>Channel<%= link_to "", channelcreate_path, class: "fa fa-plus alink blink" %></h3>
        <ul>
        <% @mchannel.each do |mchannel|%>
            <li>
            <%=link_to mchannel.channel_name,channelchat_url(:channel_id => mchannel.id), method: :post ,class: "alink" %>
            <% @channel_count.each do |count|%>
                <% if mchannel.id==count.channel_id%>               
               &nbsp &nbsp &nbsp &nbsp &nbsp<%= count.count%>
                <% end %>
                <% end %>
            </li>
        <% end %>
        </ul>
    </div>

    <div class="memberlist2">
        <h3>Member List</h3>
        <ul>
          
        <% @muser.each do |muser|%>
            <li>
            <%= link_to muser.user_name, dirchat_url(:id => muser.id), class: "alink"   %>         
                <% @dir_count.each do |count|%>
                    <% if muser.user_name==count.user_name%>               
                    &nbsp &nbsp &nbsp &nbsp &nbsp<%= count.count%>
                <% end %>
                    
            <% end %>
            </li>
            <% end %>
        </ul>
    </div>

    <div class="dmemberinvite">
        <h3>Member Invite<%= link_to "", memberinvite_path, class: "fa fa-plus alink blink" %></h3>
    </div>

</div>